name: ds-shap
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - backports.zstd=1.2.0=py311hd694d0d_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py311h7e844b6_1
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311haec20ae_3
  - cycler=0.12.1=pyhcf101f3_2
  - fonttools=4.61.1=py311he13f9b5_0
  - freetype=2.14.1=h694c41f_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h14c5de8_0
  - idna=3.11=pyhd8ed1ab_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py311h591569d_2
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcxx=21.1.8=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libpng=1.6.53=h380d223_0
  - libsqlite=3.51.1=hd09e2f1_1
  - libtiff=4.7.1=ha0a348c_1
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - llvmlite=0.46.0=py311hb26b958_0
  - matplotlib=3.10.8=py311h6eed73b_0
  - matplotlib-base=3.10.8=py311h48d7e91_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - numba=0.63.1=py311hfe9595b_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hca9a5ca_2
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=12.0.0=py311h56465c8_2
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=h00291cd_1002
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h74c2667_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311he13f9b5_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.3=h68b038d_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.8.0=np2py311heeb2b4f_1
  - scipy=1.16.3=py311hd77d3c2_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shap=0.50.0=cpu_py311hbaaddbb_0
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - statsmodels=0.14.6=py311ha837bc1_0
  - tabulate=0.9.0=pyhcf101f3_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=hf689a15_3
  - tornado=6.5.4=py311ha2bb86f_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - unicodedata2=17.0.0=py311hf197a57_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - wbgapi=1.0.12=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - yaml=0.2.5=h4132b18_3
  - zlib-ng=2.3.2=h8bce59a_1
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - anyio==4.12.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - cffi==2.0.0
      - comm==0.2.3
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.1
      - fqdn==1.5.1
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - mpmath==1.3.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - send2trash==1.8.3
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - traitlets==5.14.3
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
prefix: /Users/mnn/miniforge3/envs/ds-shap
