name: ds-text
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=78.1=h14c5de8_0
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - liblzma=5.8.1=hd471939_2
  - libsqlite=3.51.1=hd09e2f1_1
  - libzlib=1.3.1=hd23fc13_2
  - ncurses=6.5=h0622a9a_3
  - openssl=3.6.0=h230baf5_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=h74c2667_2_cpython
  - readline=8.3=h68b038d_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=hf689a15_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.20.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - sentence-transformers==5.2.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.2.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
prefix: /Users/mnn/miniforge3/envs/ds-text
